IF(LINUX)
    FIND_PATH(WIICPP_INCLUDE_DIR
            NAMES wiic.h
            PATHS /usr/local/include/wiic  )
	FIND_LIBRARY(WIICPP_LIBRARY
            NAMES libwiicpp
            PATHS /usr/local/lib )
	IF(WIICPP_INCLUDE_DIR AND WIICPP_LIBRARY)
		SET(WIICPP_FOUND TRUE)
	ENDIF(WIICPP_INCLUDE_DIR AND WIICPP_LIBRARY)
ENDIF(LINUX)

IF (WIICPP_FOUND)
   IF (NOT WIICPP_FIND_QUIETLY)
      MESSAGE(WARNING "Found WIICPP: ${WIICPP_LIBRARY}")
   ENDIF (NOT WIICPP_FIND_QUIETLY)
   SET(WIICPP_INCLUDE_DIR : ${WIICPP_INCLUDE_DIR})
   SET(WIICPP_LIBRARY : ${WIICPP_LIBRARY})
ELSE (WIICPP_FOUND)
   IF (WIICPP_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Wicpp. Please install the Wiicpp package")
   ENDIF (WIICPP_FIND_REQUIRED)
ENDIF (WIICPP_FOUND)
