/*
 * Generated by PetriLab - https://sigilence-technologies.com/petrilab
 * Version 3.0.0-beta1
 */

#include "../Deplacement.h"
#include "../Moteur.h"
#include "../Servo.h"
#include "../Utils.h"
#include <cstdint>
#include <petrilab/Cpp/Action.h>
#include <petrilab/Cpp/MemberPetriDynamicLib.h>
#include <petrilab/Cpp/PetriDebug.h>
#include <petrilab/Cpp/PetriUtils.h>
#include <petrilab/Cpp/VarSlot.h>
#include <petrilab/Cpp/Variable.h>

using namespace Petri;

struct FillResult {
	void* start;
	void* end;
};

static void fillVariables(Petri::VarSlot& variables) {}

extern "C" Petri_actionResult_t ActiverAbeille_entryInit(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	if(!_PETRI_PRIVATE_GET_VARIABLES_.isFirstSlot()) {
		_PETRI_PRIVATE_GET_VARIABLES_.pushVariables(0);
	}
	fillVariables(_PETRI_PRIVATE_GET_VARIABLES_);
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

extern "C" Petri_actionResult_t ActiverAbeille_exitAction(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	auto _PETRI_PRIVATE_EXEC_RESULT_ = static_cast<actionResult_t>(Petri::Utility::doNothing());
	_PETRI_PRIVATE_GET_VARIABLES_.pop();
	_PETRI_PRIVATE_GET_VARIABLES_.pushReturnValues(0);
	return _PETRI_PRIVATE_EXEC_RESULT_;
}

static Petri_actionResult_t state_3_invocation(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static bool transition_5_invocation(VarSlot const& _PETRI_PRIVATE_GET_VARIABLES_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_4_invocation(VarSlot const& _PETRI_PRIVATE_GET_VARIABLES_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}


extern "C" FillResult ActiverAbeille_fill(PetriNet& petriNet,
                                          std::uint64_t entitiesOffset,
                                          bool firstLevel,
                                          Petri_actionResult_t (*initEntryPtr)(VarSlot&),
                                          Petri_actionResult_t (*exitActionPtr)(VarSlot&)) {
	auto& state_0 = petriNet.addAction(Action(0 + entitiesOffset, "Root_Entry", initEntryPtr, 0), firstLevel);
	auto& state_2 = petriNet.addAction(Action(2 + entitiesOffset, "Root_End", exitActionPtr, 1), false);
	auto& state_3 = petriNet.addAction(Action(3 + entitiesOffset, "Root_BEGIN", &state_3_invocation, 0), false);


	state_0.addTransition(5 + entitiesOffset, "Root_Entry_to_BEGIN", state_3, &transition_5_invocation);
	state_3.addTransition(4 + entitiesOffset, "Root_", state_2, &transition_4_invocation);

	return (FillResult){&state_0, &state_2};
}
namespace Petri {
	namespace Generated {
		namespace ActiverAbeille {
			std::unique_ptr<::Petri::PetriNet> createPetriNet() {
				auto petriNet = std::make_unique<PetriNet>("ActiverAbeille", 0);
				petriNet->setLogVerbosity(PetriNet::VerbosityNothing);
				ActiverAbeille_fill(*petriNet, 0, true, &ActiverAbeille_entryInit, &ActiverAbeille_exitAction);
				fillVariables(petriNet->variables());
				return petriNet;
			}

			std::unique_ptr<::Petri::PetriDebug> createDebugPetriNet() {
				auto petriNet = std::make_unique<PetriDebug>("ActiverAbeille", 0);
				petriNet->setLogVerbosity(PetriNet::VerbosityNothing);
				ActiverAbeille_fill(*petriNet, 0, true, &ActiverAbeille_entryInit, &ActiverAbeille_exitAction);
				fillVariables(petriNet->variables());
				return petriNet;
			}
		}
	}
}

extern "C" void* ActiverAbeille_create() {
	return Petri::Generated::ActiverAbeille::createPetriNet().release();
}

extern "C" void* ActiverAbeille_createDebug() {
	return Petri::Generated::ActiverAbeille::createDebugPetriNet().release();
}

extern "C" char* ActiverAbeille_evaluate(void* vars, char const* libPath) {
	return Petri::Utility::loadEvaluateAndInvoke(vars, libPath, "ActiverAbeille");
}
extern "C" char const* ActiverAbeille_getHash() {
	return "E0BB865D2A4AFA8511E498BBA69CCC6429CE0FF7F17499A194D00727BBF3E573";
}


extern "C" void* ActiverAbeille_createLibForEditor() {
	return ::Petri::MemberPetriDynamicLib::libForEditor("ActiverAbeille", 12346);
}
