/*
 * Generated by PetriLab - https://sigilence-technologies.com/petrilab
 * Version 3.0.0-beta1
 */

#include "../Deplacement.h"
#include "../Moteur.h"
#include "../Servo.h"
#include "../Utils.h"
#include <cstdint>
#include <petrilab/Cpp/Action.h>
#include <petrilab/Cpp/MemberPetriDynamicLib.h>
#include <petrilab/Cpp/PetriDebug.h>
#include <petrilab/Cpp/PetriUtils.h>
#include <petrilab/Cpp/VarSlot.h>
#include <petrilab/Cpp/Variable.h>

using namespace Petri;

struct FillResult {
	void* start;
	void* end;
};

enum Petri_Var_Enum : std::uint_fast32_t { Petri_Var_Enum_Vresult = 0 };

static void fillVariables(Petri::VarSlot& variables) {
	variables[Petri_Var_Enum_Vresult].setName("$result");
	variables[Petri_Var_Enum_Vresult].setDefaultValue(0);
}

extern "C" Petri_actionResult_t ActiverAbeille_entryInit(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	if(!_PETRI_PRIVATE_GET_VARIABLES_.isFirstSlot()) {
		_PETRI_PRIVATE_GET_VARIABLES_.pushVariables(1);
	}
	fillVariables(_PETRI_PRIVATE_GET_VARIABLES_);
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

extern "C" Petri_actionResult_t ActiverAbeille_exitAction(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	auto _PETRI_PRIVATE_EXEC_RESULT_ = static_cast<actionResult_t>(Petri::Utility::doNothing());
	auto _PETRI_PRIVATE_GET_RETURN_VALUE_0_ = _PETRI_PRIVATE_GET_VARIABLES_[Petri_Var_Enum_Vresult].value();
	_PETRI_PRIVATE_GET_VARIABLES_.pop();
	_PETRI_PRIVATE_GET_VARIABLES_.pushReturnValues(1);
	_PETRI_PRIVATE_GET_VARIABLES_[0].setName("result");
	_PETRI_PRIVATE_GET_VARIABLES_[0].value() = _PETRI_PRIVATE_GET_RETURN_VALUE_0_;
	return _PETRI_PRIVATE_EXEC_RESULT_;
}

static Petri_actionResult_t state_5_invocation(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(20_cm)));
}

static Petri_actionResult_t state_6_invocation(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	return static_cast<actionResult_t>(tournerAbsolu(static_cast<Angle>(45_deg)));
}

static Petri_actionResult_t state_7_invocation(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(20_cm)));
}

static Petri_actionResult_t state_8_invocation(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	return static_cast<actionResult_t>(tournerAbsolu(static_cast<Angle>(70_deg)));
}

static Petri_actionResult_t state_9_invocation(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(40_cm)));
}

static Petri_actionResult_t state_10_invocation(VarSlot& _PETRI_PRIVATE_GET_VARIABLES_) {
	return static_cast<actionResult_t>(ouvrirAbeilleD());
}

static bool transition_17_invocation(VarSlot const& _PETRI_PRIVATE_GET_VARIABLES_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_11_invocation(VarSlot const& _PETRI_PRIVATE_GET_VARIABLES_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_12_invocation(VarSlot const& _PETRI_PRIVATE_GET_VARIABLES_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_13_invocation(VarSlot const& _PETRI_PRIVATE_GET_VARIABLES_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_14_invocation(VarSlot const& _PETRI_PRIVATE_GET_VARIABLES_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_15_invocation(VarSlot const& _PETRI_PRIVATE_GET_VARIABLES_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_16_invocation(VarSlot const& _PETRI_PRIVATE_GET_VARIABLES_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}


extern "C" FillResult ActiverAbeille_fill(PetriNet& petriNet,
                                          std::uint64_t entitiesOffset,
                                          bool firstLevel,
                                          Petri_actionResult_t (*initEntryPtr)(VarSlot&),
                                          Petri_actionResult_t (*exitActionPtr)(VarSlot&)) {
	auto& state_0 = petriNet.addAction(Action(0 + entitiesOffset, "Root_Entry", initEntryPtr, 0), firstLevel);
	auto& state_4 = petriNet.addAction(Action(4 + entitiesOffset, "Root_End", exitActionPtr, 1), false);
	auto& state_5 = petriNet.addAction(Action(5 + entitiesOffset, "Root_Avancer", &state_5_invocation, 0), false);
	auto& state_6 = petriNet.addAction(Action(6 + entitiesOffset, "Root_6", &state_6_invocation, 1), false);
	auto& state_7 = petriNet.addAction(Action(7 + entitiesOffset, "Root_7", &state_7_invocation, 1), false);
	auto& state_8 = petriNet.addAction(Action(8 + entitiesOffset, "Root_9", &state_8_invocation, 1), false);
	auto& state_9 = petriNet.addAction(Action(9 + entitiesOffset, "Root_10", &state_9_invocation, 1), false);
	auto& state_10 = petriNet.addAction(Action(10 + entitiesOffset, "Root_8", &state_10_invocation, 1), false);


	state_0.addTransition(17 + entitiesOffset, "Root_Entry_to_Avancer", state_5, &transition_17_invocation);
	state_5.addTransition(11 + entitiesOffset, "Root_13", state_6, &transition_11_invocation);
	state_6.addTransition(12 + entitiesOffset, "Root_14", state_7, &transition_12_invocation);
	state_8.addTransition(13 + entitiesOffset, "Root_17", state_9, &transition_13_invocation);
	state_9.addTransition(14 + entitiesOffset, "Root_18", state_4, &transition_14_invocation);
	state_7.addTransition(15 + entitiesOffset, "Root_15", state_10, &transition_15_invocation);
	state_10.addTransition(16 + entitiesOffset, "Root_16", state_8, &transition_16_invocation);

	return (FillResult){&state_0, &state_4};
}
namespace Petri {
	namespace Generated {
		namespace ActiverAbeille {
			std::unique_ptr<::Petri::PetriNet> createPetriNet() {
				auto petriNet = std::make_unique<PetriNet>("ActiverAbeille", 1);
				petriNet->setLogVerbosity(PetriNet::VerbosityNothing);
				ActiverAbeille_fill(*petriNet, 0, true, &ActiverAbeille_entryInit, &ActiverAbeille_exitAction);
				fillVariables(petriNet->variables());
				return petriNet;
			}

			std::unique_ptr<::Petri::PetriDebug> createDebugPetriNet() {
				auto petriNet = std::make_unique<PetriDebug>("ActiverAbeille", 1);
				petriNet->setLogVerbosity(PetriNet::VerbosityNothing);
				ActiverAbeille_fill(*petriNet, 0, true, &ActiverAbeille_entryInit, &ActiverAbeille_exitAction);
				fillVariables(petriNet->variables());
				return petriNet;
			}
		}
	}
}

extern "C" void* ActiverAbeille_create() {
	return Petri::Generated::ActiverAbeille::createPetriNet().release();
}

extern "C" void* ActiverAbeille_createDebug() {
	return Petri::Generated::ActiverAbeille::createDebugPetriNet().release();
}

extern "C" char* ActiverAbeille_evaluate(void* vars, char const* libPath) {
	return Petri::Utility::loadEvaluateAndInvoke(vars, libPath, "ActiverAbeille");
}
extern "C" char const* ActiverAbeille_getHash() {
	return "03ADD824BA0211103162879BD6D29FABF323CD0A6ED84CD11F21007CDDDED361";
}


extern "C" void* ActiverAbeille_createLibForEditor() {
	return ::Petri::MemberPetriDynamicLib::libForEditor("ActiverAbeille", 12346);
}
