/*
 * Generated by the petri net editor - https://github.com/rems4e/petri
 * Version 2.0.1
 */

#ifndef PETRI_GENERATED_Homologation_H
#define PETRI_GENERATED_Homologation_H

#include "Runtime/Cpp/MemberPetriDynamicLib.h"
#include <memory>

namespace Petri {
	namespace Generated {
		inline std::unique_ptr<::Petri::PetriDynamicLib> Homologation_createLib() {
			return std::make_unique<::Petri::MemberPetriDynamicLib>(false, "Homologation", "Homologation", 12346);
		}
	}
}

#endif
