/*
 * Generated by the petri net editor - https://github.com/rems4e/petri
 * Version 2.1.8
 */

#ifndef PETRI_GENERATED_IA_H
#define PETRI_GENERATED_IA_H

#include <memory>
#include <petrilab/Cpp/MemberPetriDynamicLib.h>

namespace Petri {
	namespace Generated {
		inline std::unique_ptr<::Petri::PetriDynamicLib> IA_createLib(std::string const& customPath = "") {
			return std::make_unique<::Petri::MemberPetriDynamicLib>(false, "IA", 12346, customPath);
		}
	}
}

#endif
