/*
 * Generated by the petri net editor - https://github.com/rems4e/petri
 * Version 2.1.7
 */

#include "../Deplacement.h"
#include "../Servo.h"
#include "../Utils.h"
#include "Runtime/Cpp/Action.h"
#include "Runtime/Cpp/Atomic.h"
#include "Runtime/Cpp/MemberPetriDynamicLib.h"
#include "Runtime/Cpp/PetriDebug.h"
#include "Runtime/Cpp/PetriUtils.h"
#include <cstdint>

#define EXPORT extern "C"
#define PETRI_PREFIX "IA2017"

using namespace Petri;

struct FillResult {
	void* start;
	void* end;
};

extern "C" FillResult
    attraperBoules_fill(PetriNet& petriNet, std::uint64_t entitiesOffset, std::uint_fast32_t variablesOffset, bool firstLevel);
extern "C" FillResult
    attraperBoules_fill(PetriNet& petriNet, std::uint64_t entitiesOffset, std::uint_fast32_t variablesOffset, bool firstLevel);
extern "C" FillResult
    poserCylindre_fill(PetriNet& petriNet, std::uint64_t entitiesOffset, std::uint_fast32_t variablesOffset, bool firstLevel);
extern "C" FillResult
    poserCylindre_fill(PetriNet& petriNet, std::uint64_t entitiesOffset, std::uint_fast32_t variablesOffset, bool firstLevel);
extern "C" FillResult
    poserCylindre_fill(PetriNet& petriNet, std::uint64_t entitiesOffset, std::uint_fast32_t variablesOffset, bool firstLevel);
extern "C" FillResult
    poserCylindre_fill(PetriNet& petriNet, std::uint64_t entitiesOffset, std::uint_fast32_t variablesOffset, bool firstLevel);
extern "C" FillResult
    poserCylindre_fill(PetriNet& petriNet, std::uint64_t entitiesOffset, std::uint_fast32_t variablesOffset, bool firstLevel);
extern "C" FillResult
    poserCylindre_fill(PetriNet& petriNet, std::uint64_t entitiesOffset, std::uint_fast32_t variablesOffset, bool firstLevel);
enum class Petri_Var_Enum : std::uint_fast32_t {
	V_MAX_CYLINDRES = 0,
	V_PLACES_ROBOT = 1,
	Vcylindres_fusee = 2,
	Vdist_0 = 3,
	Vdist_45 = 4,
	Vdist_m_45 = 5,
	Vis_boules = 6,
	Vis_cyl_bas_droite = 7,
	Vis_cyl_droit = 8,
	Vis_cyl_fond = 9,
	Vis_cyl_gauche = 10,
	Vis_cyl_rail_45 = 11,
	Vis_cyl_rail_m_45 = 12,
	Vis_cyl_sortie = 13,
	Vnbr_poses_rail_0 = 14,
	Vnbr_poses_rail_45 = 15,
	Vnbr_poses_rail_m_45 = 16
};

static Petri_actionResult_t state_0_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_16_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_75_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(reculerDe(static_cast<Distance>(1_m)));
}

static Petri_actionResult_t state_76_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::pause(static_cast<std::chrono::nanoseconds>(25s)));
}

static Petri_actionResult_t state_30_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_407_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_408_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_0)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_409_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_m_45)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_410_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_45)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_411_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::V_MAX_CYLINDRES)).value() = 5;
		return {};
	})());
}

static Petri_actionResult_t state_412_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vcylindres_fusee)).value() = 4;
		return {};
	})());
}

static Petri_actionResult_t state_413_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_45)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_414_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_m_45)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_415_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_droit)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_416_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_gauche)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_417_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_sortie)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_418_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_boules)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_419_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_fond)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_420_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_bas_droite)).value() = 0;
		return {};
	})());
}

static Petri_actionResult_t state_421_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::V_PLACES_ROBOT)).value() = 2;
		return {};
	})());
}

static Petri_actionResult_t state_33_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_619_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_620_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_621_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(allerA(static_cast<Distance>(83_cm), static_cast<Distance>(1_m)));
}

static Petri_actionResult_t state_622_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(tournerAbsolu(static_cast<Angle>(145_deg)));
}

static Petri_actionResult_t state_623_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::printText(
	    static_cast<std::string const&>("Echec de AllerA - prendre cylindre [50_cm ; 90_cm]")));
}

static Petri_actionResult_t state_625_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_626_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(tournerAbsolu(static_cast<Angle>(-70_deg)));
}

static Petri_actionResult_t state_627_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(20_cm)));
}

static Petri_actionResult_t state_628_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(stockerCylindre());
}

static Petri_actionResult_t state_624_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_630_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_631_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(stockerCylindre());
}

static Petri_actionResult_t state_632_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_633_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(56_cm)));
}

static Petri_actionResult_t state_634_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(
	    Petri::Utility::printText(static_cast<std::string const&>("J'ai stocké le cylindre en[1_m; 1 . 4_m]")));
}

static Petri_actionResult_t state_635_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::printText(
	    static_cast<std::string const&>("Warning : je n'ai pas stocké le cylindre en [1_m;1.4_m] !!")));
}

static Petri_actionResult_t state_35_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_653_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_654_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_655_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_m_45)).value() = 1;
		return {};
	})());
}

static Petri_actionResult_t state_656_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(allerA(static_cast<Distance>(50_cm), static_cast<Distance>(90_cm)));
}

static Petri_actionResult_t state_657_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(tournerAbsolu(static_cast<Angle>(-45_deg)));
}

static Petri_actionResult_t state_658_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::printText(
	    static_cast<std::string const&>("Echec de AllerA - prendre cylindre [90_cm ; 60_cm]")));
}

static Petri_actionResult_t state_660_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_659_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_662_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_663_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(stockerCylindre());
}

static Petri_actionResult_t state_664_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_665_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(25_cm)));
}

static Petri_actionResult_t state_666_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(
	    Petri::Utility::printText(static_cast<std::string const&>("J'ai stocké le cylindre en[1_m; 1 . 4_m]")));
}

static Petri_actionResult_t state_667_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::printText(
	    static_cast<std::string const&>("Warning : je n'ai pas stocké le cylindre en [1_m;1.4_m] !!")));
}

static Petri_actionResult_t state_36_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_682_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_683_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_684_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_fond)).value() = 1;
		return {};
	})());
}

static Petri_actionResult_t state_685_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(allerA(static_cast<Distance>(50_cm), static_cast<Distance>(80_cm)));
}

static Petri_actionResult_t state_686_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(tournerAbsolu(static_cast<Angle>(-65_deg)));
}

static Petri_actionResult_t state_687_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::printText(
	    static_cast<std::string const&>("Echec de AllerA - prendre cylindre [50_cm ; 90_cm]")));
}

static Petri_actionResult_t state_689_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_688_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_691_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_692_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(stockerCylindre());
}

static Petri_actionResult_t state_693_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_694_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(48_cm)));
}

static Petri_actionResult_t state_695_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(
	    Petri::Utility::printText(static_cast<std::string const&>("J'ai stocké le cylindre en[1_m; 1 . 4_m]")));
}

static Petri_actionResult_t state_696_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::printText(
	    static_cast<std::string const&>("Warning : je n'ai pas stocké le cylindre en [1_m;1.4_m] !!")));
}

static Petri_actionResult_t state_697_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(reculerDe(static_cast<Distance>(50_cm)));
}

static Petri_actionResult_t state_37_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_714_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_715_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_716_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(orienterPinceAttraper());
}

static Petri_actionResult_t state_717_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(pencherPinceDevant());
}

static Petri_actionResult_t state_718_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(ouvrirPince());
}

static Petri_actionResult_t state_719_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(ascenseurCylindreSol());
}

static Petri_actionResult_t state_720_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(setVitesseAngulaireLente());
}

static Petri_actionResult_t state_72_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_769_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_802_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(allerA(static_cast<Distance>(75_cm), static_cast<Distance>(65_cm)));
}

static Petri_actionResult_t state_803_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(tournerAbsolu(static_cast<Angle>(-45_deg)));
}

static Petri_actionResult_t state_804_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(
	    Petri::Utility::printText(static_cast<std::string const&>("Echec de AllerA - poser_ds_rails_-45")));
}

static Petri_actionResult_t state_805_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_806_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_m_45)).value() =
		    _PETRI_PRIVATE_GET_ENTITY_
		        .getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_m_45))
		        .value() +
		    getNbrCylindres();
		return {};
	})());
}

static Petri_actionResult_t state_73_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_815_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_816_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(([&_PETRI_PRIVATE_GET_ENTITY_]() -> ResultatAction {
		_PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_0)).value() =
		    _PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_0)).value() +
		    getNbrCylindres();
		return {};
	})());
}

static Petri_actionResult_t state_817_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(allerA(static_cast<Distance>(1.5_m), static_cast<Distance>(1.2_m)));
}

static Petri_actionResult_t state_818_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(tournerAbsolu(static_cast<Angle>(-90_deg)));
}

static Petri_actionResult_t state_819_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(
	    Petri::Utility::printText(static_cast<std::string const&>("Echec de AllerA - poser_ds_rails_0")));
}

static Petri_actionResult_t state_820_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_853_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(10_cm)));
}

static Petri_actionResult_t state_74_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_862_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(Petri::Utility::doNothing());
}

static Petri_actionResult_t state_863_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(10_cm)));
}

static Petri_actionResult_t state_864_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(tournerAbsolu(static_cast<Angle>(-30_deg)));
}

static Petri_actionResult_t state_865_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(40_cm)));
}

static Petri_actionResult_t state_866_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(tournerAbsolu(static_cast<Angle>(-90_deg)));
}

static Petri_actionResult_t state_867_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_) {
	return static_cast<actionResult_t>(avancerDe(static_cast<Distance>(35_cm)));
}

static bool transition_919_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_878_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_881_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_882_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_883_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_884_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_885_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_886_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_887_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_888_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_889_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_902_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_422_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_423_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_424_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_425_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_426_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_427_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_428_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_429_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_430_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_431_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_432_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_433_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_434_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_435_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_908_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_641_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_bas_droite)).value() == 1;
}

static bool transition_642_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_bas_droite)).value() == 0;
}

static bool transition_643_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ == static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_644_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ != static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_645_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_646_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_647_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_648_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_649_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_650_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_651_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_907_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_636_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_637_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ == static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_638_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ != static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_639_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_640_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_910_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_673_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_m_45)).value() == 1;
}

static bool transition_674_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_m_45)).value() == 0;
}

static bool transition_675_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ == static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_676_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ != static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_677_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_678_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_679_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_680_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_681_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_909_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_668_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_669_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_670_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ == static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_671_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ != static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_672_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_912_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_704_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_fond)).value() == 1;
}

static bool transition_705_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ENTITY_.getVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_fond)).value() == 0;
}

static bool transition_706_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ == static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_707_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ != static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_708_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_709_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_710_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_711_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_712_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_911_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_698_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_699_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ == static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_700_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ != static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_701_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_702_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_703_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_913_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_721_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_722_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_723_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_724_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_725_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_726_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_727_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_728_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_916_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_807_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ == static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_808_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ != static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_809_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_810_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_811_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_812_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_813_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_917_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_854_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ == static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_855_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return _PETRI_PRIVATE_GET_ACTION_RESULT_ != static_cast<actionResult_t>(ResultatAction::REUSSI);
}

static bool transition_856_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_857_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_858_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_859_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_860_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_861_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_918_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_868_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_869_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_870_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_871_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}

static bool transition_872_invocation(Entity& _PETRI_PRIVATE_GET_ENTITY_, Petri_actionResult_t _PETRI_PRIVATE_GET_ACTION_RESULT_) {
	return true;
}


EXPORT FillResult IA2017_fill(PetriNet& petriNet, std::uint64_t entitiesOffset, std::uint_fast32_t variablesOffset, bool firstLevel) {
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::V_MAX_CYLINDRES) + variablesOffset,
	                     "$_MAX_CYLINDRES");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::V_PLACES_ROBOT) + variablesOffset,
	                     "$_PLACES_ROBOT");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vcylindres_fusee) + variablesOffset,
	                     "$cylindres_fusee");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vdist_0) + variablesOffset, "$dist_0");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vdist_45) + variablesOffset, "$dist_45");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vdist_m_45) + variablesOffset, "$dist_m_45");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_boules) + variablesOffset, "$is_boules");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_bas_droite) + variablesOffset,
	                     "$is_cyl_bas_droite");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_droit) + variablesOffset,
	                     "$is_cyl_droit");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_fond) + variablesOffset,
	                     "$is_cyl_fond");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_gauche) + variablesOffset,
	                     "$is_cyl_gauche");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_45) + variablesOffset,
	                     "$is_cyl_rail_45");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_m_45) + variablesOffset,
	                     "$is_cyl_rail_m_45");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_sortie) + variablesOffset,
	                     "$is_cyl_sortie");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_0) + variablesOffset,
	                     "$nbr_poses_rail_0");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_45) + variablesOffset,
	                     "$nbr_poses_rail_45");
	petriNet.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_m_45) + variablesOffset,
	                     "$nbr_poses_rail_m_45");
	auto& state_0 =
	    petriNet.addAction(Action(petriNet, 0 + entitiesOffset, "Root_Entry", &state_0_invocation, 0), firstLevel, variablesOffset);
	auto& state_16 =
	    petriNet.addAction(Action(petriNet, 16 + entitiesOffset, "Root_End", &state_16_invocation, 1), false, variablesOffset);
	auto& state_75 =
	    petriNet.addAction(Action(petriNet, 75 + entitiesOffset, "Root_1002", &state_75_invocation, 1), false, variablesOffset);
	auto& state_76 =
	    petriNet.addAction(Action(petriNet, 76 + entitiesOffset, "Root_1003", &state_76_invocation, 1), false, variablesOffset);
	auto& state_30 =
	    petriNet.addAction(Action(petriNet, 30 + entitiesOffset, "Root_Variables_Entry", &state_30_invocation, 0), false, variablesOffset);
	auto& state_407 =
	    petriNet.addAction(Action(petriNet, 407 + entitiesOffset, "Root_Variables_End", &state_407_invocation, 1), false, variablesOffset);
	auto& state_408 =
	    petriNet.addAction(Action(petriNet, 408 + entitiesOffset, "Root_Variables_rail[0]", &state_408_invocation, 0), false, variablesOffset);
	state_408.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_0));
	auto& state_409 =
	    petriNet.addAction(Action(petriNet, 409 + entitiesOffset, "Root_Variables_rail[-45]", &state_409_invocation, 1), false, variablesOffset);
	state_409.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_m_45));
	auto& state_410 =
	    petriNet.addAction(Action(petriNet, 410 + entitiesOffset, "Root_Variables_rail[45]", &state_410_invocation, 1), false, variablesOffset);
	state_410.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_45));
	auto& state_411 =
	    petriNet.addAction(Action(petriNet, 411 + entitiesOffset, "Root_Variables_407", &state_411_invocation, 1), false, variablesOffset);
	state_411.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::V_MAX_CYLINDRES));
	auto& state_412 =
	    petriNet.addAction(Action(petriNet, 412 + entitiesOffset, "Root_Variables_fusee", &state_412_invocation, 1), false, variablesOffset);
	state_412.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vcylindres_fusee));
	auto& state_413 =
	    petriNet.addAction(Action(petriNet, 413 + entitiesOffset, "Root_Variables_cyl[45]", &state_413_invocation, 1), false, variablesOffset);
	state_413.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_45));
	auto& state_414 =
	    petriNet.addAction(Action(petriNet, 414 + entitiesOffset, "Root_Variables_cyl[-45]", &state_414_invocation, 1), false, variablesOffset);
	state_414.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_m_45));
	auto& state_415 =
	    petriNet.addAction(Action(petriNet, 415 + entitiesOffset, "Root_Variables_cyl[droit]", &state_415_invocation, 1), false, variablesOffset);
	state_415.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_droit));
	auto& state_416 =
	    petriNet.addAction(Action(petriNet, 416 + entitiesOffset, "Root_Variables_cyl[gauche]", &state_416_invocation, 1), false, variablesOffset);
	state_416.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_gauche));
	auto& state_417 =
	    petriNet.addAction(Action(petriNet, 417 + entitiesOffset, "Root_Variables_cyl[debut]", &state_417_invocation, 1), false, variablesOffset);
	state_417.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_sortie));
	auto& state_418 =
	    petriNet.addAction(Action(petriNet, 418 + entitiesOffset, "Root_Variables_boules[debut]", &state_418_invocation, 1),
	                       false,
	                       variablesOffset);
	state_418.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_boules));
	auto& state_419 =
	    petriNet.addAction(Action(petriNet, 419 + entitiesOffset, "Root_Variables_cyl[fond]", &state_419_invocation, 1), false, variablesOffset);
	state_419.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_fond));
	auto& state_420 =
	    petriNet.addAction(Action(petriNet, 420 + entitiesOffset, "Root_Variables_cyl[bas_droite]", &state_420_invocation, 1),
	                       false,
	                       variablesOffset);
	state_420.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_bas_droite));
	auto& state_421 =
	    petriNet.addAction(Action(petriNet, 421 + entitiesOffset, "Root_Variables_1411", &state_421_invocation, 1), false, variablesOffset);
	state_421.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::V_PLACES_ROBOT));
	auto& state_33 =
	    petriNet.addAction(Action(petriNet, 33 + entitiesOffset, "Root_cyl[0.2;1.4]_Entry", &state_33_invocation, 1), false, variablesOffset);
	auto& state_619 =
	    petriNet.addAction(Action(petriNet, 619 + entitiesOffset, "Root_cyl[0.2;1.4]_End", &state_619_invocation, 1), false, variablesOffset);
	auto& state_620 =
	    petriNet.addAction(Action(petriNet, 620 + entitiesOffset, "Root_cyl[0.2;1.4]_26", &state_620_invocation, 0), false, variablesOffset);
	auto& state_621 =
	    petriNet.addAction(Action(petriNet, 621 + entitiesOffset, "Root_cyl[0.2;1.4]_270", &state_621_invocation, 1), false, variablesOffset);
	auto& state_622 =
	    petriNet.addAction(Action(petriNet, 622 + entitiesOffset, "Root_cyl[0.2;1.4]_164", &state_622_invocation, 1), false, variablesOffset);
	auto& state_623 =
	    petriNet.addAction(Action(petriNet, 623 + entitiesOffset, "Root_cyl[0.2;1.4]_194", &state_623_invocation, 1), false, variablesOffset);
	auto& state_625 =
	    petriNet.addAction(Action(petriNet, 625 + entitiesOffset, "Root_cyl[0.2;1.4]_330", &state_625_invocation, 1), false, variablesOffset);
	auto& state_626 =
	    petriNet.addAction(Action(petriNet, 626 + entitiesOffset, "Root_cyl[0.2;1.4]_988", &state_626_invocation, 1), false, variablesOffset);
	auto& state_627 =
	    petriNet.addAction(Action(petriNet, 627 + entitiesOffset, "Root_cyl[0.2;1.4]_990", &state_627_invocation, 1), false, variablesOffset);
	auto& state_628 =
	    petriNet.addAction(Action(petriNet, 628 + entitiesOffset, "Root_cyl[0.2;1.4]_993", &state_628_invocation, 1), false, variablesOffset);
	auto& state_624 =
	    petriNet.addAction(Action(petriNet, 624 + entitiesOffset, "Root_cyl[0.2;1.4]_action_Entry", &state_624_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_630 =
	    petriNet.addAction(Action(petriNet, 630 + entitiesOffset, "Root_cyl[0.2;1.4]_action_End", &state_630_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_631 =
	    petriNet.addAction(Action(petriNet, 631 + entitiesOffset, "Root_cyl[0.2;1.4]_action_86", &state_631_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_632 =
	    petriNet.addAction(Action(petriNet, 632 + entitiesOffset, "Root_cyl[0.2;1.4]_action_110", &state_632_invocation, 0),
	                       false,
	                       variablesOffset);
	auto& state_633 =
	    petriNet.addAction(Action(petriNet, 633 + entitiesOffset, "Root_cyl[0.2;1.4]_action_235", &state_633_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_634 =
	    petriNet.addAction(Action(petriNet, 634 + entitiesOffset, "Root_cyl[0.2;1.4]_action_268", &state_634_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_635 =
	    petriNet.addAction(Action(petriNet, 635 + entitiesOffset, "Root_cyl[0.2;1.4]_action_274", &state_635_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_35 =
	    petriNet.addAction(Action(petriNet, 35 + entitiesOffset, "Root_cyl[0.9;0.6]_Entry", &state_35_invocation, 1), false, variablesOffset);
	auto& state_653 =
	    petriNet.addAction(Action(petriNet, 653 + entitiesOffset, "Root_cyl[0.9;0.6]_End", &state_653_invocation, 1), false, variablesOffset);
	auto& state_654 =
	    petriNet.addAction(Action(petriNet, 654 + entitiesOffset, "Root_cyl[0.9;0.6]_26", &state_654_invocation, 0), false, variablesOffset);
	auto& state_655 =
	    petriNet.addAction(Action(petriNet, 655 + entitiesOffset, "Root_cyl[0.9;0.6]_26", &state_655_invocation, 1), false, variablesOffset);
	state_655.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_m_45));
	auto& state_656 =
	    petriNet.addAction(Action(petriNet, 656 + entitiesOffset, "Root_cyl[0.9;0.6]_270", &state_656_invocation, 1), false, variablesOffset);
	auto& state_657 =
	    petriNet.addAction(Action(petriNet, 657 + entitiesOffset, "Root_cyl[0.9;0.6]_164", &state_657_invocation, 1), false, variablesOffset);
	auto& state_658 =
	    petriNet.addAction(Action(petriNet, 658 + entitiesOffset, "Root_cyl[0.9;0.6]_194", &state_658_invocation, 1), false, variablesOffset);
	auto& state_660 =
	    petriNet.addAction(Action(petriNet, 660 + entitiesOffset, "Root_cyl[0.9;0.6]_330", &state_660_invocation, 1), false, variablesOffset);
	auto& state_659 =
	    petriNet.addAction(Action(petriNet, 659 + entitiesOffset, "Root_cyl[0.9;0.6]_action_Entry", &state_659_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_662 =
	    petriNet.addAction(Action(petriNet, 662 + entitiesOffset, "Root_cyl[0.9;0.6]_action_End", &state_662_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_663 =
	    petriNet.addAction(Action(petriNet, 663 + entitiesOffset, "Root_cyl[0.9;0.6]_action_86", &state_663_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_664 =
	    petriNet.addAction(Action(petriNet, 664 + entitiesOffset, "Root_cyl[0.9;0.6]_action_110", &state_664_invocation, 0),
	                       false,
	                       variablesOffset);
	auto& state_665 =
	    petriNet.addAction(Action(petriNet, 665 + entitiesOffset, "Root_cyl[0.9;0.6]_action_235", &state_665_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_666 =
	    petriNet.addAction(Action(petriNet, 666 + entitiesOffset, "Root_cyl[0.9;0.6]_action_268", &state_666_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_667 =
	    petriNet.addAction(Action(petriNet, 667 + entitiesOffset, "Root_cyl[0.9;0.6]_action_274", &state_667_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_36 =
	    petriNet.addAction(Action(petriNet, 36 + entitiesOffset, "Root_cyl[0.8;0.15]_Entry", &state_36_invocation, 1), false, variablesOffset);
	auto& state_682 =
	    petriNet.addAction(Action(petriNet, 682 + entitiesOffset, "Root_cyl[0.8;0.15]_End", &state_682_invocation, 1), false, variablesOffset);
	auto& state_683 =
	    petriNet.addAction(Action(petriNet, 683 + entitiesOffset, "Root_cyl[0.8;0.15]_26", &state_683_invocation, 0), false, variablesOffset);
	auto& state_684 =
	    petriNet.addAction(Action(petriNet, 684 + entitiesOffset, "Root_cyl[0.8;0.15]_26", &state_684_invocation, 1), false, variablesOffset);
	state_684.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_fond));
	auto& state_685 =
	    petriNet.addAction(Action(petriNet, 685 + entitiesOffset, "Root_cyl[0.8;0.15]_270", &state_685_invocation, 1), false, variablesOffset);
	auto& state_686 =
	    petriNet.addAction(Action(petriNet, 686 + entitiesOffset, "Root_cyl[0.8;0.15]_164", &state_686_invocation, 1), false, variablesOffset);
	auto& state_687 =
	    petriNet.addAction(Action(petriNet, 687 + entitiesOffset, "Root_cyl[0.8;0.15]_194", &state_687_invocation, 1), false, variablesOffset);
	auto& state_689 =
	    petriNet.addAction(Action(petriNet, 689 + entitiesOffset, "Root_cyl[0.8;0.15]_330", &state_689_invocation, 1), false, variablesOffset);
	auto& state_688 =
	    petriNet.addAction(Action(petriNet, 688 + entitiesOffset, "Root_cyl[0.8;0.15]_action_Entry", &state_688_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_691 =
	    petriNet.addAction(Action(petriNet, 691 + entitiesOffset, "Root_cyl[0.8;0.15]_action_End", &state_691_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_692 =
	    petriNet.addAction(Action(petriNet, 692 + entitiesOffset, "Root_cyl[0.8;0.15]_action_86", &state_692_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_693 =
	    petriNet.addAction(Action(petriNet, 693 + entitiesOffset, "Root_cyl[0.8;0.15]_action_110", &state_693_invocation, 0),
	                       false,
	                       variablesOffset);
	auto& state_694 =
	    petriNet.addAction(Action(petriNet, 694 + entitiesOffset, "Root_cyl[0.8;0.15]_action_235", &state_694_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_695 =
	    petriNet.addAction(Action(petriNet, 695 + entitiesOffset, "Root_cyl[0.8;0.15]_action_268", &state_695_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_696 =
	    petriNet.addAction(Action(petriNet, 696 + entitiesOffset, "Root_cyl[0.8;0.15]_action_274", &state_696_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_697 =
	    petriNet.addAction(Action(petriNet, 697 + entitiesOffset, "Root_cyl[0.8;0.15]_action_1180", &state_697_invocation, 1),
	                       false,
	                       variablesOffset);
	auto& state_37 =
	    petriNet.addAction(Action(petriNet, 37 + entitiesOffset, "Root_Init_Meca_Entry", &state_37_invocation, 1), false, variablesOffset);
	auto& state_714 =
	    petriNet.addAction(Action(petriNet, 714 + entitiesOffset, "Root_Init_Meca_End", &state_714_invocation, 3), false, variablesOffset);
	auto& state_715 =
	    petriNet.addAction(Action(petriNet, 715 + entitiesOffset, "Root_Init_Meca_1190", &state_715_invocation, 0), false, variablesOffset);
	auto& state_716 =
	    petriNet.addAction(Action(petriNet, 716 + entitiesOffset, "Root_Init_Meca_1191", &state_716_invocation, 1), false, variablesOffset);
	auto& state_717 =
	    petriNet.addAction(Action(petriNet, 717 + entitiesOffset, "Root_Init_Meca_1192", &state_717_invocation, 1), false, variablesOffset);
	auto& state_718 =
	    petriNet.addAction(Action(petriNet, 718 + entitiesOffset, "Root_Init_Meca_1193", &state_718_invocation, 1), false, variablesOffset);
	auto& state_719 =
	    petriNet.addAction(Action(petriNet, 719 + entitiesOffset, "Root_Init_Meca_1194", &state_719_invocation, 1), false, variablesOffset);
	auto& state_720 =
	    petriNet.addAction(Action(petriNet, 720 + entitiesOffset, "Root_Init_Meca_999", &state_720_invocation, 1), false, variablesOffset);
	auto& state_72 =
	    petriNet.addAction(Action(petriNet, 72 + entitiesOffset, "Root_rail[-45]_Entry", &state_72_invocation, 1), false, variablesOffset);
	auto& state_769 =
	    petriNet.addAction(Action(petriNet, 769 + entitiesOffset, "Root_rail[-45]_End", &state_769_invocation, 1), false, variablesOffset);
	auto& state_802 =
	    petriNet.addAction(Action(petriNet, 802 + entitiesOffset, "Root_rail[-45]_270", &state_802_invocation, 0), false, variablesOffset);
	auto& state_803 =
	    petriNet.addAction(Action(petriNet, 803 + entitiesOffset, "Root_rail[-45]_164", &state_803_invocation, 1), false, variablesOffset);
	auto& state_804 =
	    petriNet.addAction(Action(petriNet, 804 + entitiesOffset, "Root_rail[-45]_194", &state_804_invocation, 1), false, variablesOffset);
	auto& state_805 =
	    petriNet.addAction(Action(petriNet, 805 + entitiesOffset, "Root_rail[-45]_334", &state_805_invocation, 1), false, variablesOffset);
	auto& state_806 =
	    petriNet.addAction(Action(petriNet, 806 + entitiesOffset, "Root_rail[-45]_406", &state_806_invocation, 1), false, variablesOffset);
	state_806.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_m_45));
	auto state_770_endpoints = poserCylindre_fill(petriNet, entitiesOffset + 770, petriNet.variablesCount(), false);
	auto& state_73 =
	    petriNet.addAction(Action(petriNet, 73 + entitiesOffset, "Root_rail[0]_Entry", &state_73_invocation, 1), false, variablesOffset);
	auto& state_815 =
	    petriNet.addAction(Action(petriNet, 815 + entitiesOffset, "Root_rail[0]_End", &state_815_invocation, 1), false, variablesOffset);
	auto& state_816 =
	    petriNet.addAction(Action(petriNet, 816 + entitiesOffset, "Root_rail[0]_26", &state_816_invocation, 1), false, variablesOffset);
	state_816.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vnbr_poses_rail_0));
	auto& state_817 =
	    petriNet.addAction(Action(petriNet, 817 + entitiesOffset, "Root_rail[0]_270", &state_817_invocation, 0), false, variablesOffset);
	auto& state_818 =
	    petriNet.addAction(Action(petriNet, 818 + entitiesOffset, "Root_rail[0]_164", &state_818_invocation, 1), false, variablesOffset);
	auto& state_819 =
	    petriNet.addAction(Action(petriNet, 819 + entitiesOffset, "Root_rail[0]_194", &state_819_invocation, 1), false, variablesOffset);
	auto& state_820 =
	    petriNet.addAction(Action(petriNet, 820 + entitiesOffset, "Root_rail[0]_334", &state_820_invocation, 1), false, variablesOffset);
	auto& state_853 =
	    petriNet.addAction(Action(petriNet, 853 + entitiesOffset, "Root_rail[0]_1372", &state_853_invocation, 1), false, variablesOffset);
	auto state_821_endpoints = poserCylindre_fill(petriNet, entitiesOffset + 821, petriNet.variablesCount(), false);
	auto& state_74 =
	    petriNet.addAction(Action(petriNet, 74 + entitiesOffset, "Root_centre_table_Entry", &state_74_invocation, 1), false, variablesOffset);
	auto& state_862 =
	    petriNet.addAction(Action(petriNet, 862 + entitiesOffset, "Root_centre_table_End", &state_862_invocation, 1), false, variablesOffset);
	auto& state_863 =
	    petriNet.addAction(Action(petriNet, 863 + entitiesOffset, "Root_centre_table_1474", &state_863_invocation, 0), false, variablesOffset);
	auto& state_864 =
	    petriNet.addAction(Action(petriNet, 864 + entitiesOffset, "Root_centre_table_906", &state_864_invocation, 1), false, variablesOffset);
	auto& state_865 =
	    petriNet.addAction(Action(petriNet, 865 + entitiesOffset, "Root_centre_table_907", &state_865_invocation, 1), false, variablesOffset);
	auto& state_866 =
	    petriNet.addAction(Action(petriNet, 866 + entitiesOffset, "Root_centre_table_911", &state_866_invocation, 1), false, variablesOffset);
	auto& state_867 =
	    petriNet.addAction(Action(petriNet, 867 + entitiesOffset, "Root_centre_table_913", &state_867_invocation, 1), false, variablesOffset);


	auto& transition_919 =
	    state_0.addTransition(919 + entitiesOffset, "Root_Entry_to_Variables_Entry", state_30, &transition_919_invocation);
	auto& transition_878 = state_407.addTransition(878 + entitiesOffset, "Root_1204", state_37, &transition_878_invocation);
	auto& transition_881 = state_653.addTransition(881 + entitiesOffset, "Root_904", state_36, &transition_881_invocation);
	auto& transition_882 = state_682.addTransition(882 + entitiesOffset, "Root_905", state_72, &transition_882_invocation);
	auto& transition_883 = state_769.addTransition(883 + entitiesOffset, "Root_906", state_16, &transition_883_invocation);
	auto& transition_884 = state_714.addTransition(884 + entitiesOffset, "Root_938", state_74, &transition_884_invocation);
	auto& transition_885 = state_862.addTransition(885 + entitiesOffset, "Root_939", state_33, &transition_885_invocation);
	auto& transition_886 = state_619.addTransition(886 + entitiesOffset, "Root_998", state_73, &transition_886_invocation);
	auto& transition_887 = state_815.addTransition(887 + entitiesOffset, "Root_1004", state_75, &transition_887_invocation);
	auto& transition_888 = state_75.addTransition(888 + entitiesOffset, "Root_1005", state_76, &transition_888_invocation);
	auto& transition_889 = state_76.addTransition(889 + entitiesOffset, "Root_1006", state_35, &transition_889_invocation);
	auto& transition_902 =
	    state_30.addTransition(902 + entitiesOffset, "Root_Variables_Entry_to_rail[0]", state_408, &transition_902_invocation);
	auto& transition_422 =
	    state_408.addTransition(422 + entitiesOffset, "Root_Variables_404", state_409, &transition_422_invocation);
	auto& transition_423 =
	    state_409.addTransition(423 + entitiesOffset, "Root_Variables_405", state_410, &transition_423_invocation);
	auto& transition_424 =
	    state_410.addTransition(424 + entitiesOffset, "Root_Variables_408", state_411, &transition_424_invocation);
	auto& transition_425 =
	    state_411.addTransition(425 + entitiesOffset, "Root_Variables_532", state_412, &transition_425_invocation);
	auto& transition_426 =
	    state_412.addTransition(426 + entitiesOffset, "Root_Variables_486", state_413, &transition_426_invocation);
	auto& transition_427 =
	    state_413.addTransition(427 + entitiesOffset, "Root_Variables_488", state_414, &transition_427_invocation);
	auto& transition_428 =
	    state_414.addTransition(428 + entitiesOffset, "Root_Variables_492", state_415, &transition_428_invocation);
	auto& transition_429 =
	    state_415.addTransition(429 + entitiesOffset, "Root_Variables_494", state_416, &transition_429_invocation);
	auto& transition_430 =
	    state_416.addTransition(430 + entitiesOffset, "Root_Variables_496", state_417, &transition_430_invocation);
	auto& transition_431 =
	    state_417.addTransition(431 + entitiesOffset, "Root_Variables_1258", state_419, &transition_431_invocation);
	auto& transition_432 =
	    state_419.addTransition(432 + entitiesOffset, "Root_Variables_1261", state_420, &transition_432_invocation);
	auto& transition_433 =
	    state_420.addTransition(433 + entitiesOffset, "Root_Variables_1262", state_418, &transition_433_invocation);
	auto& transition_434 =
	    state_418.addTransition(434 + entitiesOffset, "Root_Variables_1412", state_421, &transition_434_invocation);
	auto& transition_435 =
	    state_421.addTransition(435 + entitiesOffset, "Root_Variables_1413", state_407, &transition_435_invocation);
	auto& transition_908 =
	    state_33.addTransition(908 + entitiesOffset, "Root_cyl[0.2;1.4]_Entry_to_26", state_620, &transition_908_invocation);
	auto& transition_641 =
	    state_620.addTransition(641 + entitiesOffset, "Root_cyl[0.2;1.4]_30", state_625, &transition_641_invocation);
	transition_641.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_bas_droite));
	auto& transition_642 =
	    state_620.addTransition(642 + entitiesOffset, "Root_cyl[0.2;1.4]_271", state_621, &transition_642_invocation);
	transition_642.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_bas_droite));
	auto& transition_643 =
	    state_621.addTransition(643 + entitiesOffset, "Root_cyl[0.2;1.4]_165", state_622, &transition_643_invocation);
	auto& transition_644 =
	    state_621.addTransition(644 + entitiesOffset, "Root_cyl[0.2;1.4]_195", state_623, &transition_644_invocation);
	auto& transition_645 =
	    state_622.addTransition(645 + entitiesOffset, "Root_cyl[0.2;1.4]_381", state_624, &transition_645_invocation);
	auto& transition_646 =
	    state_623.addTransition(646 + entitiesOffset, "Root_cyl[0.2;1.4]_331", state_625, &transition_646_invocation);
	auto& transition_647 =
	    state_625.addTransition(647 + entitiesOffset, "Root_cyl[0.2;1.4]_1507", state_619, &transition_647_invocation);
	auto& transition_648 =
	    state_630.addTransition(648 + entitiesOffset, "Root_cyl[0.2;1.4]_989", state_626, &transition_648_invocation);
	auto& transition_649 =
	    state_626.addTransition(649 + entitiesOffset, "Root_cyl[0.2;1.4]_991", state_627, &transition_649_invocation);
	auto& transition_650 =
	    state_627.addTransition(650 + entitiesOffset, "Root_cyl[0.2;1.4]_994", state_628, &transition_650_invocation);
	auto& transition_651 =
	    state_628.addTransition(651 + entitiesOffset, "Root_cyl[0.2;1.4]_995", state_625, &transition_651_invocation);
	auto& transition_907 =
	    state_624.addTransition(907 + entitiesOffset, "Root_cyl[0.2;1.4]_action_Entry_to_110", state_632, &transition_907_invocation);
	auto& transition_636 =
	    state_632.addTransition(636 + entitiesOffset, "Root_cyl[0.2;1.4]_action_235", state_633, &transition_636_invocation);
	auto& transition_637 =
	    state_631.addTransition(637 + entitiesOffset, "Root_cyl[0.2;1.4]_action_273", state_634, &transition_637_invocation);
	auto& transition_638 =
	    state_631.addTransition(638 + entitiesOffset, "Root_cyl[0.2;1.4]_action_275", state_635, &transition_638_invocation);
	auto& transition_639 =
	    state_633.addTransition(639 + entitiesOffset, "Root_cyl[0.2;1.4]_action_273", state_631, &transition_639_invocation);
	auto& transition_640 =
	    state_631.addTransition(640 + entitiesOffset, "Root_cyl[0.2;1.4]_action_987", state_630, &transition_640_invocation);
	auto& transition_910 =
	    state_35.addTransition(910 + entitiesOffset, "Root_cyl[0.9;0.6]_Entry_to_26", state_654, &transition_910_invocation);
	auto& transition_673 =
	    state_654.addTransition(673 + entitiesOffset, "Root_cyl[0.9;0.6]_30", state_660, &transition_673_invocation);
	transition_673.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_m_45));
	auto& transition_674 =
	    state_654.addTransition(674 + entitiesOffset, "Root_cyl[0.9;0.6]_271", state_656, &transition_674_invocation);
	transition_674.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_rail_m_45));
	auto& transition_675 =
	    state_656.addTransition(675 + entitiesOffset, "Root_cyl[0.9;0.6]_165", state_657, &transition_675_invocation);
	auto& transition_676 =
	    state_656.addTransition(676 + entitiesOffset, "Root_cyl[0.9;0.6]_195", state_658, &transition_676_invocation);
	auto& transition_677 =
	    state_657.addTransition(677 + entitiesOffset, "Root_cyl[0.9;0.6]_381", state_659, &transition_677_invocation);
	auto& transition_678 =
	    state_662.addTransition(678 + entitiesOffset, "Root_cyl[0.9;0.6]_382", state_655, &transition_678_invocation);
	auto& transition_679 =
	    state_658.addTransition(679 + entitiesOffset, "Root_cyl[0.9;0.6]_331", state_660, &transition_679_invocation);
	auto& transition_680 =
	    state_655.addTransition(680 + entitiesOffset, "Root_cyl[0.9;0.6]_332", state_660, &transition_680_invocation);
	auto& transition_681 =
	    state_660.addTransition(681 + entitiesOffset, "Root_cyl[0.9;0.6]_333", state_653, &transition_681_invocation);
	auto& transition_909 =
	    state_659.addTransition(909 + entitiesOffset, "Root_cyl[0.9;0.6]_action_Entry_to_110", state_664, &transition_909_invocation);
	auto& transition_668 =
	    state_664.addTransition(668 + entitiesOffset, "Root_cyl[0.9;0.6]_action_235", state_665, &transition_668_invocation);
	auto& transition_669 =
	    state_663.addTransition(669 + entitiesOffset, "Root_cyl[0.9;0.6]_action_272", state_662, &transition_669_invocation);
	auto& transition_670 =
	    state_663.addTransition(670 + entitiesOffset, "Root_cyl[0.9;0.6]_action_273", state_666, &transition_670_invocation);
	auto& transition_671 =
	    state_663.addTransition(671 + entitiesOffset, "Root_cyl[0.9;0.6]_action_275", state_667, &transition_671_invocation);
	auto& transition_672 =
	    state_665.addTransition(672 + entitiesOffset, "Root_cyl[0.9;0.6]_action_273", state_663, &transition_672_invocation);
	auto& transition_912 =
	    state_36.addTransition(912 + entitiesOffset, "Root_cyl[0.8;0.15]_Entry_to_26", state_683, &transition_912_invocation);
	auto& transition_704 =
	    state_683.addTransition(704 + entitiesOffset, "Root_cyl[0.8;0.15]_30", state_689, &transition_704_invocation);
	transition_704.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_fond));
	auto& transition_705 =
	    state_683.addTransition(705 + entitiesOffset, "Root_cyl[0.8;0.15]_271", state_685, &transition_705_invocation);
	transition_705.addVariable(static_cast<std::uint_fast32_t>(Petri_Var_Enum::Vis_cyl_fond));
	auto& transition_706 =
	    state_685.addTransition(706 + entitiesOffset, "Root_cyl[0.8;0.15]_165", state_686, &transition_706_invocation);
	auto& transition_707 =
	    state_685.addTransition(707 + entitiesOffset, "Root_cyl[0.8;0.15]_195", state_687, &transition_707_invocation);
	auto& transition_708 =
	    state_686.addTransition(708 + entitiesOffset, "Root_cyl[0.8;0.15]_381", state_688, &transition_708_invocation);
	auto& transition_709 =
	    state_691.addTransition(709 + entitiesOffset, "Root_cyl[0.8;0.15]_382", state_684, &transition_709_invocation);
	auto& transition_710 =
	    state_687.addTransition(710 + entitiesOffset, "Root_cyl[0.8;0.15]_331", state_689, &transition_710_invocation);
	auto& transition_711 =
	    state_684.addTransition(711 + entitiesOffset, "Root_cyl[0.8;0.15]_332", state_689, &transition_711_invocation);
	auto& transition_712 =
	    state_689.addTransition(712 + entitiesOffset, "Root_cyl[0.8;0.15]_1507", state_682, &transition_712_invocation);
	auto& transition_911 =
	    state_688.addTransition(911 + entitiesOffset, "Root_cyl[0.8;0.15]_action_Entry_to_110", state_693, &transition_911_invocation);
	auto& transition_698 =
	    state_693.addTransition(698 + entitiesOffset, "Root_cyl[0.8;0.15]_action_235", state_694, &transition_698_invocation);
	auto& transition_699 =
	    state_692.addTransition(699 + entitiesOffset, "Root_cyl[0.8;0.15]_action_273", state_695, &transition_699_invocation);
	auto& transition_700 =
	    state_692.addTransition(700 + entitiesOffset, "Root_cyl[0.8;0.15]_action_275", state_696, &transition_700_invocation);
	auto& transition_701 =
	    state_694.addTransition(701 + entitiesOffset, "Root_cyl[0.8;0.15]_action_273", state_692, &transition_701_invocation);
	auto& transition_702 =
	    state_692.addTransition(702 + entitiesOffset, "Root_cyl[0.8;0.15]_action_1181", state_697, &transition_702_invocation);
	auto& transition_703 =
	    state_697.addTransition(703 + entitiesOffset, "Root_cyl[0.8;0.15]_action_1182", state_691, &transition_703_invocation);
	auto& transition_913 =
	    state_37.addTransition(913 + entitiesOffset, "Root_Init_Meca_Entry_to_1190", state_715, &transition_913_invocation);
	auto& transition_721 =
	    state_716.addTransition(721 + entitiesOffset, "Root_Init_Meca_1196", state_717, &transition_721_invocation);
	auto& transition_722 =
	    state_716.addTransition(722 + entitiesOffset, "Root_Init_Meca_1197", state_718, &transition_722_invocation);
	auto& transition_723 =
	    state_716.addTransition(723 + entitiesOffset, "Root_Init_Meca_1198", state_719, &transition_723_invocation);
	auto& transition_724 =
	    state_719.addTransition(724 + entitiesOffset, "Root_Init_Meca_1199", state_714, &transition_724_invocation);
	auto& transition_725 =
	    state_718.addTransition(725 + entitiesOffset, "Root_Init_Meca_1200", state_714, &transition_725_invocation);
	auto& transition_726 =
	    state_717.addTransition(726 + entitiesOffset, "Root_Init_Meca_1201", state_714, &transition_726_invocation);
	auto& transition_727 =
	    state_720.addTransition(727 + entitiesOffset, "Root_Init_Meca_1000", state_716, &transition_727_invocation);
	auto& transition_728 =
	    state_715.addTransition(728 + entitiesOffset, "Root_Init_Meca_1001", state_720, &transition_728_invocation);
	auto& transition_916 =
	    state_72.addTransition(916 + entitiesOffset, "Root_rail[-45]_Entry_to_270", state_802, &transition_916_invocation);
	auto& transition_807 =
	    state_802.addTransition(807 + entitiesOffset, "Root_rail[-45]_165", state_803, &transition_807_invocation);
	auto& transition_808 =
	    state_802.addTransition(808 + entitiesOffset, "Root_rail[-45]_195", state_804, &transition_808_invocation);
	auto& transition_809 =
	    state_804.addTransition(809 + entitiesOffset, "Root_rail[-45]_335", state_805, &transition_809_invocation);
	auto& transition_810 =
	    state_805.addTransition(810 + entitiesOffset, "Root_rail[-45]_337", state_769, &transition_810_invocation);
	auto& transition_811 =
	    state_803.addTransition(811 + entitiesOffset, "Root_rail[-45]_950", state_806, &transition_811_invocation);
	auto& transition_812 = state_806.addTransition(812 + entitiesOffset,
	                                               "Root_rail[-45]_951",
	                                               (*reinterpret_cast<Action*>(state_770_endpoints.start)),
	                                               &transition_812_invocation);
	auto& transition_813 =
	    (*reinterpret_cast<Action*>(state_770_endpoints.end)).addTransition(813 + entitiesOffset, "Root_rail[-45]_952", state_805, &transition_813_invocation);
	auto& transition_917 =
	    state_73.addTransition(917 + entitiesOffset, "Root_rail[0]_Entry_to_270", state_817, &transition_917_invocation);
	auto& transition_854 = state_817.addTransition(854 + entitiesOffset, "Root_rail[0]_165", state_818, &transition_854_invocation);
	auto& transition_855 = state_817.addTransition(855 + entitiesOffset, "Root_rail[0]_195", state_819, &transition_855_invocation);
	auto& transition_856 = state_819.addTransition(856 + entitiesOffset, "Root_rail[0]_335", state_820, &transition_856_invocation);
	auto& transition_857 = state_820.addTransition(857 + entitiesOffset, "Root_rail[0]_337", state_815, &transition_857_invocation);
	auto& transition_858 = state_816.addTransition(858 + entitiesOffset,
	                                               "Root_rail[0]_955",
	                                               (*reinterpret_cast<Action*>(state_821_endpoints.start)),
	                                               &transition_858_invocation);
	auto& transition_859 =
	    (*reinterpret_cast<Action*>(state_821_endpoints.end)).addTransition(859 + entitiesOffset, "Root_rail[0]_956", state_820, &transition_859_invocation);
	auto& transition_860 = state_818.addTransition(860 + entitiesOffset, "Root_rail[0]_1373", state_853, &transition_860_invocation);
	auto& transition_861 = state_853.addTransition(861 + entitiesOffset, "Root_rail[0]_1374", state_816, &transition_861_invocation);
	auto& transition_918 =
	    state_74.addTransition(918 + entitiesOffset, "Root_centre_table_Entry_to_1474", state_863, &transition_918_invocation);
	auto& transition_868 =
	    state_863.addTransition(868 + entitiesOffset, "Root_centre_table_908", state_864, &transition_868_invocation);
	auto& transition_869 =
	    state_864.addTransition(869 + entitiesOffset, "Root_centre_table_909", state_865, &transition_869_invocation);
	auto& transition_870 =
	    state_865.addTransition(870 + entitiesOffset, "Root_centre_table_912", state_866, &transition_870_invocation);
	auto& transition_871 =
	    state_866.addTransition(871 + entitiesOffset, "Root_centre_table_914", state_867, &transition_871_invocation);
	auto& transition_872 =
	    state_867.addTransition(872 + entitiesOffset, "Root_centre_table_937", state_862, &transition_872_invocation);

	return (FillResult){&state_0, &state_16};
}

EXPORT void* IA2017_create() {
	auto petriNet = std::make_unique<PetriNet>(PETRI_PREFIX);
	IA2017_fill(*petriNet, 0, 0, true);
	return petriNet.release();
}

EXPORT void* IA2017_createDebug() {
	auto petriNet = std::make_unique<PetriDebug>(PETRI_PREFIX);
	IA2017_fill(*petriNet, 0, 0, true);
	return petriNet.release();
}

EXPORT char const* IA2017_getHash() {
	return "5FE4EDE3CAEEB0969FFBEA3672331CD536C935B3";
}

#define NO_C_PETRI_NET
#include "Runtime/C/detail/Types.hpp"

EXPORT void* IA2017_createLibForEditor() {
	return new ::PetriDynamicLib{std::make_unique<::Petri::MemberPetriDynamicLib>(false, "IA2017", 12346)};
}
