/*
 * Generated by PetriLab - https://sigilence-technologies.com/petrilab
 * Version 3.0.0-beta1
 */

#ifndef PETRI_GENERATED_IA2018_H
#define PETRI_GENERATED_IA2018_H

#include <petrilab/Cpp/MemberPetriDynamicLib.h>
#include <memory>

namespace Petri {
	namespace Generated {
		namespace IA2018 {
			enum Petri_Param_Enum : std::uint_fast32_t {Petri_Param_Enum_Vaction = 0};

			std::unique_ptr<::Petri::PetriNet> createPetriNet();
			std::unique_ptr<::Petri::PetriDebug> createDebugPetriNet();

			inline std::unique_ptr<::Petri::PetriDynamicLib> createLib(std::string const &customPath = "") {
				return std::make_unique<::Petri::MemberPetriDynamicLib>(false, "IA2018", 12346, customPath);
			}
		}
	}
}

#endif

