/*
 * Generated by the petri net editor - https://github.com/rems4e/petri
 * Version 2.1.7
 */

#ifndef PETRI_GENERATED_IA2017_H
#define PETRI_GENERATED_IA2017_H

#include <memory>
#include <petri/Runtime/Cpp/MemberPetriDynamicLib.h>

namespace Petri {
	namespace Generated {
		inline std::unique_ptr<::Petri::PetriDynamicLib> IA2017_createLib(std::string const& customPath = "") {
			return std::make_unique<::Petri::MemberPetriDynamicLib>(false, "IA2017", 12346, customPath);
		}
	}
}

#endif
