/*
 * Generated by the petri net editor - https://github.com/rems4e/petri
 * Version 2.1.5
 */

#ifndef PETRI_GENERATED_ouvrirFesses_H
#define PETRI_GENERATED_ouvrirFesses_H

#include "Runtime/Cpp/MemberPetriDynamicLib.h"
#include <memory>

namespace Petri {
	namespace Generated {
		inline std::unique_ptr<::Petri::PetriDynamicLib> ouvrirFesses_createLib(std::string const& customPath = "") {
			return std::make_unique<::Petri::MemberPetriDynamicLib>(false, "ouvrirFesses", 12346, customPath);
		}
	}
}

#endif
