// IDCartes2012.h - les IDs des cartes
// En-tête utilisé par le simu et par l'IE

#ifndef IDCARTES_2012_H
#define IDCARTES_2012_H

namespace IDCartes2012
{
	enum IdCarte
	{
		ID_CARTE_CAN_USB 							= 0,
		ID_CARTE_DEPLACEMENT 						= 1,
		ID_CARTE_ASSERVISSEMENT_LINGOT_TOTEM 		= 2,
		ID_CARTE_ASSERVISSEMENT_MOISSONNEUSE		= 3,
		ID_CARTE_ASSERVISSEMENT_COFFRE				= 4,
		ID_CARTE_CONTACTEURS_DEPART 				= 5,
		ID_CARTE_SERVOS_NOVA_PIECE_TOTEM 			= 6,
		ID_CARTE_SERVOS_NOVA_COFFRE_ET_CALE			= 7,
		ID_CARTE_SERVOS_NOVA_CARTE_ET_LINGOT_TOTEM	= 8,
		ID_CARTE_POS_ADV							= 11,
		ID_CARTE_ALIMENTATION 						= 12
	};
}
#endif
