import sys
sys.path.append('../../..')
from scons_tools import *

#---------------------------------------------
# Liste des sources
#---------------------------------------------
sources = Split("""
	../enable.c
	../fullscreen.c
	../glext.c
	../image.c
	../init.c
	../input.c
	../joystick.c
	../stream.c
	../tga.c
	../thread.c
	../time.c
	../window.c
	cocoa_enable.m
	cocoa_fullscreen.m
	cocoa_glext.m
	cocoa_init.m
	cocoa_joystick.m
	cocoa_thread.c
	cocoa_time.m
	cocoa_window.m
""")

#---------------------------------------------
# options de l'environement
#---------------------------------------------
env = createEnvironment([])


env.Append(CPPPATH=['..','.'])

#---------------------------------------------
# generation de la library
#---------------------------------------------
env.StaticLibrary('../../lib/glfw', sources)
