# simulateur/GLFW/src/win32/SConstruct

import sys
sys.path.append('../../../..')
from scons_tools import *

#---------------------------------------------
# Liste des sources
#---------------------------------------------
sources = Split("""
	../enable.c
	../fullscreen.c
	../glext.c
	../image.c
	../init.c
	../input.c
	../joystick.c
	../stream.c
	../tga.c
	../thread.c
	../time.c
	../window.c
	win32_enable.c
	win32_fullscreen.c
	win32_glext.c
	win32_init.c
	win32_joystick.c
	win32_thread.c
	win32_time.c
	win32_window.c
""")

#---------------------------------------------
# options de l'environement
#---------------------------------------------
env = createEnvironment()

env.Append(CPPPATH=['.', '..'])

#---------------------------------------------
# generation de la library
#---------------------------------------------
env.StaticLibrary('../../lib/glfw', sources)