# commun/2015/SConstruct

import sys
sys.path.append('.')
from scons_tools import *

env = createEnvironment([])

src_list = Split("""
ConstantesCommunes2015.cpp
RobotPrincipal/Constantes2015.cpp
RobotSecondaire/Constantes2015.cpp
""")

# Rajouter les autres sources au fur et a mesure

env.StaticLibrary('Constantes2015', src_list)
