# info/commun/SConstruct

import sys
sys.path.append('..')
from scons_tools import *

SConscript('2014/SConstruct')

env = createEnvironment(['gtk', 'pthreads', 'sockets'])

src_list = Split("""
Clock/Clock.cpp
debug/CGTKwin.cpp
MathToolbox/MathUtilities.cpp
log/Log.cpp
log/LogHTML.cpp
log/LogRTF.cpp
log/LogTermVT100.cpp
log/LogTermWindows.cpp
tga/TGALoader.cpp
sockets/Socket.cpp
""")

env.StaticLibrary('Outils', src_list)
